#!/usr/bin/env python3
#
# Locust-based create/read/update workload, based on the test documents generated by the mgodatagen
# configs (locust_read_write_load_mgodatagen_*.json).
#
# The shard key range and namespace are inferred from the mgodatagen JSON config file.
#
# Example usage:
#   # First, populate the collection:
#   mgodatagen -f locust_read_write_load_mgodatagen_50GB.json --uri mongodb://localhost/?directConnection=false
#
#   # Then, run the workload (uses Locust's built-in --processes for multi-worker support):
#   locust -f locust_read_write_load.py --processes 4 --users 1000 --spawn-rate 100 --autostart --web-port 8090 --csv=locust_results --mgodatagen-config locust_read_write_load_mgodatagen_50GB.json --host mongodb://localhost/?directConnection=false
#

import json
import logging

import locust.stats

from flask import jsonify, render_template_string, request as flask_request
from locust import User, constant_pacing, events, task
from pymongo import MongoClient, ReadPreference
from random import choice, uniform
from string import ascii_letters
from time import perf_counter_ns

# Capture P50 and P99
locust.stats.PERCENTILES_TO_CHART = [0.5, 0.99]

connection_string = None
collection = None

# Populated from mgodatagen config at init time
AVG_DOC_BYTES = 0
SECONDARY_INDEX_FIELDS = []
SHARD_KEY_LENGTH = 0
COLLECTION_COUNT = 0


def compute_avg_doc_bytes(content):
    """Estimate average BSON document size from a mgodatagen content spec."""
    # BSON document: 4-byte size prefix + fields + 1-byte null terminator
    total = 5
    # _id is always present as ObjectId (12 bytes): type + "_id" + null + value
    total += 1 + 3 + 1 + 12
    for field_name, field_spec in content.items():
        field_type = field_spec.get('type', '')
        # Each element: type byte + field name + null terminator
        header = 1 + len(field_name) + 1
        if field_type == 'string':
            avg_len = (field_spec.get('minLength', 0) + field_spec.get('maxLength', 0)) / 2
            # BSON string: 4-byte length int32 + content bytes + null terminator
            total += header + 4 + avg_len + 1
        elif field_type in ('int', 'autoincrement'):
            total += header + 4
        elif field_type in ('long', 'double'):
            total += header + 8
    return round(total)


def random_shard_key():
    return ''.join(choice(ascii_letters) for _ in range(SHARD_KEY_LENGTH))


def nanos_to_millis(nanos):
    return round(nanos / 1000000.0, 2)


@events.init_command_line_parser.add_listener
def on_locust_init_command_line_parser(parser):
    parser.add_argument('--mgodatagen-config', help='Path to the mgodatagen JSON config file',
                        metavar='config', type=str, required=True)


@events.init.add_listener
def on_locust_init(environment, **kwargs):
    global connection_string
    connection_string = 'mongodb://localhost' if environment.host is None else environment.host

    # Load the mgodatagen config to infer namespace and shard key range
    with open(environment.parsed_options.mgodatagen_config) as f:
        config = json.load(f)[0]

    ns_db = config['database']
    ns_coll = config['collection']

    global SHARD_KEY_LENGTH
    SHARD_KEY_LENGTH = config['content']['shardKey']['maxLength']

    global COLLECTION_COUNT
    COLLECTION_COUNT = config['count']

    global AVG_DOC_BYTES
    AVG_DOC_BYTES = compute_avg_doc_bytes(config['content'])

    # Extract secondary index fields (exclude the shardKey index)
    global SECONDARY_INDEX_FIELDS
    for idx in config.get('indexes', []):
        field = list(idx['key'].keys())[0]
        if field != 'shardKey':
            SECONDARY_INDEX_FIELDS.append(field)

    logging.info(f'MongoDB host: {connection_string}')
    logging.info(f'Namespace: {ns_db}.{ns_coll}')
    logging.info(f'Shard key length: {SHARD_KEY_LENGTH}')
    logging.info(f'Avg document size: {AVG_DOC_BYTES} bytes')
    logging.info(f'Secondary index fields: {SECONDARY_INDEX_FIELDS}')

    global collection
    mongo_client = MongoClient(connection_string)
    collection = mongo_client[ns_db].get_collection(ns_coll, read_preference=ReadPreference.PRIMARY)

    if environment.web_ui:
        _register_custom_actions(environment.web_ui.app,
                                 environment)  # http://host:8089/custom_actions


class MongoUser(User):
    '''This user will generate a constant load of 1 request per second.'''

    wait_time = constant_pacing(1)

    def on_start(self):
        self.select_shard_key()

    @task(5)
    def select_shard_key(self):
        # Probe a random point in the key space and find the first document at
        # or after it.  This exercises the shardKey index without requiring an
        # exact match and produces a uniformly distributed random document
        # selection regardless of the actual key distribution in the collection.
        probe = random_shard_key()

        start_time = perf_counter_ns()

        shard_key_doc = collection.with_options(
            read_preference=ReadPreference.SECONDARY_PREFERRED).find_one(
                filter={'shardKey': {
                    '$gte': probe
                }}, sort=[('shardKey', 1)])

        if shard_key_doc is None:
            # Probe landed beyond the last key; wrap around to the first document.
            shard_key_doc = collection.with_options(
                read_preference=ReadPreference.SECONDARY_PREFERRED).find_one({},
                                                                             sort=[('shardKey', 1)])

        if shard_key_doc is not None:
            self.shard_key = shard_key_doc['shardKey']

        self.environment.events.request.fire(
            request_type='find_shard_key',
            name='find_shard_key',
            response_time=nanos_to_millis(perf_counter_ns() - start_time),
            response_length=0,
            exception=None,
        )

    @task(5)
    def read_by_secondary_index(self):
        if not SECONDARY_INDEX_FIELDS:
            return

        field = choice(SECONDARY_INDEX_FIELDS)
        random_key = ''.join(choice(ascii_letters) for _ in range(340))

        start_time = perf_counter_ns()

        collection.with_options(read_preference=ReadPreference.SECONDARY_PREFERRED).find_one(
            filter={field: random_key})

        self.environment.events.request.fire(
            request_type='read_secondary_index',
            name='read_secondary_index',
            response_time=nanos_to_millis(perf_counter_ns() - start_time),
            response_length=0,
            exception=None,
        )

    @task(7)
    def update_by_shard_key(self):
        start_time = perf_counter_ns()

        update_result = collection.update_one(
            filter={
                'shardKey': self.shard_key,
            },
            update={
                '$inc': {
                    'updates': 1,
                },
            },
            upsert=False,
        )

        if update_result.modified_count == 0:
            # Document was deleted externally; pick a new shard key and report as miss
            self.environment.events.request.fire(
                request_type='update_by_shard_key',
                name='update_by_shard_key',
                response_time=nanos_to_millis(perf_counter_ns() - start_time),
                response_length=0,
                exception=KeyError(f'Document for shardKey {self.shard_key} not found'),
            )
            self.select_shard_key()
            return

        self.environment.events.request.fire(
            request_type='update_by_shard_key',
            name='update_by_shard_key',
            response_time=nanos_to_millis(perf_counter_ns() - start_time),
            response_length=0,
            exception=None,
        )

    @task(3)
    def insert_new_shard_key(self):
        new_key = random_shard_key()

        start_time = perf_counter_ns()

        collection.update_one(
            filter={'shardKey': new_key},
            update={'$inc': {
                'updates': 1
            }},
            upsert=True,
        )

        self.environment.events.request.fire(
            request_type='insert_new_shard_key',
            name='insert_new_shard_key',
            response_time=nanos_to_millis(perf_counter_ns() - start_time),
            response_length=0,
            exception=None,
        )


# ---------------------------------------------------------------------------
# Custom actions web UI (accessible at http://host:8089/custom_actions)
# ---------------------------------------------------------------------------

_CUSTOM_ACTIONS_HTML = '''<!doctype html>
<html>
<head><title>Custom Actions</title></head>
<body>
<h2>Custom Actions</h2>

<h3>deleteMany_10_pct</h3>
<p>
  Computes a shardKey range covering 10% of the collection, starting at a random
  offset between 10% and 30% from the beginning, using covered index scans.
  Returns a <code>db.runCommand</code> you can paste into mongosh.
</p>
<button onclick="runAction('/custom_actions/deleteMany_10_pct', 'out_deleteMany_10_pct')">Compute deleteMany_10_pct command</button>
<pre id="out_deleteMany_10_pct" style="margin-top:1em"></pre>

<h3>fastBulkDelete_10_pct</h3>
<p>
  Same range computation as <code>deleteMany_10_pct</code> but generates a
  <code>fastBulkDelete</code> command using <code>filterIndexName</code>,
  <code>lowerBound</code>, and <code>upperBound</code>.
</p>
<button onclick="runAction('/custom_actions/fastBulkDelete_10_pct', 'out_fastBulkDelete_10_pct')">Compute fastBulkDelete_10_pct command</button>
<pre id="out_fastBulkDelete_10_pct" style="margin-top:1em"></pre>

<script>
function runAction(url, outId) {
    document.getElementById(outId).textContent = "Computing...";
    fetch(url, {method: "POST"})
        .then(r => r.json())
        .then(d => document.getElementById(outId).textContent = d.command)
        .catch(e => document.getElementById(outId).textContent = "Error: " + e);
}
</script>
</body>
</html>'''


def _register_custom_actions(app, environment):

    @app.route('/custom_actions', methods=['GET'])
    def custom_actions():
        return render_template_string(_CUSTOM_ACTIONS_HTML)

    # ---------------------------------------------------------------------------
    # Shared range computation for the 10%-deletion actions
    # ---------------------------------------------------------------------------

    def _compute_delete_range():
        # Random starting offset: between 10% and 30% from the beginning of the
        # index, so the deletion range doesn't always start at the minimum key.
        skip_docs = round(COLLECTION_COUNT * uniform(0.10, 0.30))

        # Number of documents to delete: 10% of the configured collection size.
        # Expressed via AVG_DOC_BYTES to make the relationship to data volume explicit,
        # even though the avg size cancels out algebraically.
        docs_to_delete = round(COLLECTION_COUNT * AVG_DOC_BYTES * 0.10 / AVG_DOC_BYTES)

        # Covered index scans: projection excludes _id so only the shardKey index is
        # read, with no access to the underlying documents.
        index_only = {'shardKey': 1, '_id': 0}
        start_key = next(
            collection.find({}, index_only,
                            sort=[('shardKey', 1)]).skip(skip_docs).limit(1))['shardKey']
        cutoff_key = next(
            collection.find({}, index_only, sort=[
                ('shardKey', 1)
            ]).skip(skip_docs + docs_to_delete).limit(1))['shardKey']

        return docs_to_delete, start_key, cutoff_key

    # ---------------------------------------------------------------------------
    # deleteMany - 10% of the data
    # ---------------------------------------------------------------------------

    @app.route('/custom_actions/deleteMany_10_pct', methods=['POST'])
    def deleteMany_10_pct():
        try:
            planned, start_key, cutoff_key = _compute_delete_range()
            db_name = collection.database.name
            coll_name = collection.name
            command = (
                f'db.getSiblingDB("{db_name}").runCommand({{'
                f' delete: "{coll_name}",'
                f' deletes: [{{ q: {{ shardKey: {{ $gte: "{start_key}", $lt: "{cutoff_key}" }} }}, limit: 0 }}]'
                f' }})')
            return jsonify({'planned': planned, 'command': command})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    # ---------------------------------------------------------------------------
    # fastBulkDelete - 10% of the data
    # ---------------------------------------------------------------------------

    @app.route('/custom_actions/fastBulkDelete_10_pct', methods=['POST'])
    def fastBulkDelete_10_pct():
        try:
            planned, start_key, cutoff_key = _compute_delete_range()
            db_name = collection.database.name
            coll_name = collection.name
            command = (f'db.getSiblingDB("{db_name}").runCommand({{'
                       f' fastBulkDelete: "{coll_name}",'
                       f' filterIndexName: "shardKey",'
                       f' lowerBound: {{ shardKey: "{start_key}" }},'
                       f' upperBound: {{ shardKey: "{cutoff_key}" }}'
                       f' }})')
            return jsonify({'planned': planned, 'command': command})
        except Exception as e:
            return jsonify({'error': str(e)}), 500
