#!/usr/bin/env python3
#
# Locust-based create/read/update workload, based on the test documents generated by the mgodatagen
# configs (locust_read_write_load_mgodatagen_*.json).
#
# The shard key range and namespace are inferred from the mgodatagen JSON config file.
#
# Example usage:
#   # First, populate the collection:
#   mgodatagen -f locust_read_write_load_mgodatagen_50GB.json --uri mongodb://URL/?directConnection=false
#
#   # Then, run the workload (uses Locust's built-in --processes for multi-worker support):
#   locust -f locust_read_write_load.py --processes 4 --users 2000 --spawn-rate 100 --autostart --web-port 8090 --mgodatagen-config locust_read_write_load_mgodatagen_50GB.json --host mongodb://URL/?directConnection=false
#

import json
import logging

from bson import Int64
from locust import User, constant_pacing, events, task
from pymongo import MongoClient, ReadPreference
from random import choice, randrange
from string import ascii_letters
from time import perf_counter_ns

connection_string = None
collection = None

# Populated from mgodatagen config at init time
MIN_SHARD_KEY = 0
MAX_SHARD_KEY = 0
SECONDARY_INDEX_FIELDS = []


def nanos_to_millis(nanos):
    return round(nanos / 1000000.0, 2)


@events.init_command_line_parser.add_listener
def on_locust_init_command_line_parser(parser):
    parser.add_argument('--mgodatagen-config', help='Path to the mgodatagen JSON config file',
                        metavar='config', type=str, required=True)


@events.init.add_listener
def on_locust_init(environment, **kwargs):
    global connection_string
    connection_string = 'mongodb://localhost' if environment.host is None else environment.host

    # Load the mgodatagen config to infer namespace and shard key range
    with open(environment.parsed_options.mgodatagen_config) as f:
        config = json.load(f)[0]

    ns_db = config['database']
    ns_coll = config['collection']
    count = config['count']
    start_int = config['content']['shardKey'].get('startInt', 0)

    global MIN_SHARD_KEY, MAX_SHARD_KEY
    MIN_SHARD_KEY = start_int
    MAX_SHARD_KEY = start_int + count

    # Extract secondary index fields (exclude the shardKey index)
    global SECONDARY_INDEX_FIELDS
    for idx in config.get('indexes', []):
        field = list(idx['key'].keys())[0]
        if field != 'shardKey':
            SECONDARY_INDEX_FIELDS.append(field)

    logging.info(f'MongoDB host: {connection_string}')
    logging.info(f'Namespace: {ns_db}.{ns_coll}')
    logging.info(f'Shard key range: [{MIN_SHARD_KEY}, {MAX_SHARD_KEY})')
    logging.info(f'Secondary index fields: {SECONDARY_INDEX_FIELDS}')

    global collection
    mongo_client = MongoClient(connection_string)
    collection = mongo_client[ns_db].get_collection(ns_coll, read_preference=ReadPreference.PRIMARY)


class MongoUser(User):
    '''This user will generate a constant load of 1 request per second.'''

    wait_time = constant_pacing(1)

    def on_start(self):
        self.select_shard_key()

    @task(5)
    def select_shard_key(self):
        self.shard_key = Int64(randrange(MIN_SHARD_KEY, MAX_SHARD_KEY))

        start_time = perf_counter_ns()

        shard_key_doc = collection.with_options(
            read_preference=ReadPreference.SECONDARY_PREFERRED).find_one(
                filter={
                    'shardKey': self.shard_key,
                }, )

        if shard_key_doc is None:
            start_time_insert = perf_counter_ns()

            upsert_result = collection.update_one(
                filter={
                    'shardKey': self.shard_key,
                },
                update={
                    '$inc': {
                        'updates': 1,
                    },
                },
                upsert=True,
            )
            assert upsert_result.upserted_id is not None or upsert_result.modified_count == 1, f"Upsert for {self.shard_key} didn't result in any documents being upserted"

            self.environment.events.request.fire(
                request_type='insert_shard_key',
                name='insert_shard_key',
                response_time=nanos_to_millis(perf_counter_ns() - start_time_insert),
                response_length=0,
                exception=None,
            )
        else:
            self.environment.events.request.fire(
                request_type='find_shard_key',
                name='find_shard_key',
                response_time=nanos_to_millis(perf_counter_ns() - start_time),
                response_length=0,
                exception=None,
            )

    @task(5)
    def read_by_secondary_index(self):
        if not SECONDARY_INDEX_FIELDS:
            return

        field = choice(SECONDARY_INDEX_FIELDS)
        random_key = ''.join(choice(ascii_letters) for _ in range(340))

        start_time = perf_counter_ns()

        collection.with_options(read_preference=ReadPreference.SECONDARY_PREFERRED).find_one(
            filter={field: random_key})

        self.environment.events.request.fire(
            request_type='read_secondary_index',
            name='read_secondary_index',
            response_time=nanos_to_millis(perf_counter_ns() - start_time),
            response_length=0,
            exception=None,
        )

    @task(7)
    def update_by_shard_key(self):
        start_time = perf_counter_ns()

        update_result = collection.update_one(
            filter={
                'shardKey': self.shard_key,
            },
            update={
                '$inc': {
                    'updates': 1,
                },
            },
            upsert=False,
        )

        if update_result.modified_count == 0:
            # Document was deleted externally; pick a new shard key and report as miss
            self.environment.events.request.fire(
                request_type='update_by_shard_key',
                name='update_by_shard_key',
                response_time=nanos_to_millis(perf_counter_ns() - start_time),
                response_length=0,
                exception=KeyError(f'Document for shardKey {self.shard_key} not found'),
            )
            self.select_shard_key()
            return

        self.environment.events.request.fire(
            request_type='update_by_shard_key',
            name='update_by_shard_key',
            response_time=nanos_to_millis(perf_counter_ns() - start_time),
            response_length=0,
            exception=None,
        )

    @task(3)
    def insert_new_shard_key(self):
        new_key = Int64(MAX_SHARD_KEY + randrange(0, MAX_SHARD_KEY))

        start_time = perf_counter_ns()

        collection.update_one(
            filter={'shardKey': new_key},
            update={'$inc': {
                'updates': 1
            }},
            upsert=True,
        )

        self.environment.events.request.fire(
            request_type='insert_new_shard_key',
            name='insert_new_shard_key',
            response_time=nanos_to_millis(perf_counter_ns() - start_time),
            response_length=0,
            exception=None,
        )
